import { useState, useCallback } from "react";

// ── MOCK DATA ──
const SCENARIOS = [
  { id: "s1", num: "01", title: "Governed Treasury Movement Under Explicit Policy", tier: 1, question: "Can asset movement be governed under explicit institutional policy with clear authority routing and defensible evidence?", screens: ["Asset Boundary", "Governed Movement", "Governance Participants", "Evidence Viewer"], evidence: ["Policy Trace", "Approval Chain Record", "Control Application Record", "Request-to-Execution Linkage", "Oversight Summary"], demo: "Request initiation, policy application, threshold approval, controlled execution, and full evidence trail generation.", color: "purple" },
  { id: "s2", num: "02", title: "Policy-Blocked / Exception-Governed Movement", tier: 1, question: "Can the system block what should not happen, record why, and produce a defensible exception trail?", screens: ["Governed Movement", "Governance Participants", "Evidence Viewer"], evidence: ["Policy Conflict Record", "Exception Trace", "Blocked Outcome Summary", "Oversight Exception Summary"], demo: "Movement request, policy conflict detection, blocked execution, exception recording, and oversight-ready exception evidence.", color: "fuchsia" },
  { id: "s3", num: "03", title: "Oversight-Ready Evidence Pack", tier: 1, question: "Can oversight stakeholders receive evidence they can actually use for risk, audit, compliance, or finance review?", screens: ["Evidence Viewer", "Evaluation Configuration", "Governance Participants"], evidence: ["Policy Record", "Approval Trace", "Control Trace", "Outcome Summary", "Oversight Summary"], demo: "Evidence package review from the perspective of risk, audit, compliance, or finance stakeholders.", color: "indigo" },
  { id: "s4", num: "04", title: "Selective Verification Under Confidentiality Constraint", tier: 2, question: "Can conditions be verified without unnecessary disclosure of sensitive underlying data?", screens: ["Evidence Viewer", "Asset Boundary"], evidence: ["Full Evidence View", "Selective Verification View", "Disclosure Boundary Summary"], demo: "Zero-knowledge selective verification proving governance conditions were satisfied without exposing underlying sensitive data.", color: "purple" },
  { id: "s5", num: "05", title: "Crypto-Agility / PQC Transition Readiness", tier: 2, question: "Can the operating model remain coherent as cryptographic assumptions evolve toward post-quantum standards?", screens: ["Governed Movement", "Evidence Viewer", "Evaluation Configuration"], evidence: ["Cryptographic Assurance Profile", "Current vs PQC Target View", "PQC Migration Continuity Summary"], demo: "Same governed workflow viewed under current trust basis and PQC target posture, demonstrating policy and evidence continuity.", color: "fuchsia" },
];

const PARTICIPANTS = [
  { id: "p1", name: "Alexandra Chen", fn: "Treasury / Operations", status: "active", role: "Requester", initials: "AC" },
  { id: "p2", name: "Marcus Webb", fn: "Risk Management", status: "active", role: "Approver", initials: "MW" },
  { id: "p3", name: "Diana Frost", fn: "Compliance", status: "active", role: "Reviewer", initials: "DF" },
  { id: "p4", name: "Raj Patel", fn: "Audit / Internal Audit", status: "active", role: "Oversight", initials: "RP" },
  { id: "p5", name: "Sarah Liu", fn: "Finance", status: "active", role: "Observer", initials: "SL" },
];

const ASSETS = [
  { id: "a1", name: "BTC Institutional Vault", chain: "Bitcoin", balance: "12.4821 BTC", usd: "$782,450", scope: true, control: "Multi-Approval", boundary: "Primary Reserve" },
  { id: "a2", name: "ETH Treasury Reserve", chain: "Ethereum", balance: "480.22 ETH", usd: "$1,632,748", scope: true, control: "Threshold Governance", boundary: "Operating Reserve" },
  { id: "a3", name: "USDC Liquidity Pool", chain: "Ethereum", balance: "2,500,000 USDC", usd: "$2,500,000", scope: true, control: "Policy-Governed", boundary: "Liquidity Buffer" },
  { id: "a4", name: "SOL Operations Fund", chain: "Solana", balance: "8,420.5 SOL", usd: "$1,263,075", scope: false, control: "Standard", boundary: "Operational" },
];

// ── ICONS ──
const IC = {
  Hub: () => <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><circle cx="12" cy="12" r="10"/><polygon points="16.24 7.76 14.12 14.12 7.76 16.24 9.88 9.88 16.24 7.76"/></svg>,
  Scenario: () => <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"/><path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"/></svg>,
  Asset: () => <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M20 12V8H6a2 2 0 0 1-2-2c0-1.1.9-2 2-2h12v4"/><path d="M4 6v12a2 2 0 0 0 2 2h14v-4"/><circle cx="18" cy="12" r="1"/></svg>,
  Move: () => <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><line x1="22" y1="2" x2="11" y2="13"/><polygon points="22 2 15 22 11 13 2 9 22 2"/></svg>,
  People: () => <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>,
  Evidence: () => <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/></svg>,
  Config: () => <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83-2.83l.06-.06A1.65 1.65 0 0 0 4.68 15a1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 2.83-2.83l.06.06A1.65 1.65 0 0 0 9 4.68a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 2.83l-.06.06A1.65 1.65 0 0 0 19.4 9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z"/></svg>,
  Log: () => <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><polyline points="12 8 12 12 14 14"/><circle cx="12" cy="12" r="10"/></svg>,
  Arrow: () => <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/></svg>,
  Shield: () => <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>,
  Check: () => <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"><polyline points="20 6 9 17 4 12"/></svg>,
  Block: () => <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><circle cx="12" cy="12" r="10"/><line x1="4.93" y1="4.93" x2="19.07" y2="19.07"/></svg>,
  Back: () => <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><line x1="19" y1="12" x2="5" y2="12"/><polyline points="12 19 5 12 12 5"/></svg>,
  Download: () => <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>,
};

// ── UI COMPONENTS ──
const Badge = ({ children, c = "purple" }) => {
  const m = { purple: "bg-purple-500/15 text-purple-400 border-purple-500/30", green: "bg-emerald-500/15 text-emerald-400 border-emerald-500/30", yellow: "bg-yellow-500/15 text-yellow-400 border-yellow-500/30", fuchsia: "bg-fuchsia-500/15 text-fuchsia-400 border-fuchsia-500/30", red: "bg-red-500/15 text-red-400 border-red-500/30", indigo: "bg-indigo-500/15 text-indigo-400 border-indigo-500/30", blue: "bg-blue-500/15 text-blue-400 border-blue-500/30" };
  return <span className={`fm text-xs px-2 py-0.5 border ${m[c]}`}>{children}</span>;
};
const GC = ({ children, className = "", hover, style = {}, onClick }) => (<div className={`glass ${hover ? "glass-h cursor-pointer" : ""} ${className}`} style={style} onClick={onClick}>{children}</div>);
const SL = ({ children }) => <div className="fm text-xs tracking-widest text-fuchsia-500 mb-4">[ {children} ]</div>;
const Btn = ({ children, v = "primary", className = "", onClick, disabled, full }) => {
  const base = "fm font-bold text-sm px-5 py-2.5 transition-all duration-200 cursor-pointer flex items-center justify-center gap-2 disabled:opacity-40 disabled:cursor-not-allowed";
  const vs = { primary: "bg-gradient-to-r from-purple-600 to-fuchsia-600 text-white hover:from-purple-500 hover:to-fuchsia-500 glow", secondary: "glass text-gray-300 hover:text-white", ghost: "text-gray-400 hover:text-purple-400 hover:bg-purple-500/10", danger: "bg-red-500/10 border border-red-500/30 text-red-400 hover:bg-red-500/20" };
  return <button className={`${base} ${vs[v]} ${full ? "w-full" : ""} ${className}`} onClick={onClick} disabled={disabled}>{children}</button>;
};
const InfoRow = ({ label, value, badge }) => (<div className="flex items-center justify-between py-2 border-b border-gray-800/50"><span className="fm text-xs text-gray-500">{label}</span>{badge ? <Badge c={badge.c}>{badge.t}</Badge> : <span className="fm text-xs text-gray-300">{value}</span>}</div>);

// ── AUDIT LOG ──
const AuditLog = ({ logs }) => (<div className="w-72 flex-shrink-0 flex flex-col" style={{ height: "calc(100vh - 56px)" }}><div className="p-4 border-b border-purple-500/20 flex items-center gap-2"><IC.Log /><span className="fm text-sm font-bold text-purple-400">EVALUATION_LOG</span><span className="ml-auto fm text-xs text-gray-600">{logs.length}</span></div><div className="flex-1 overflow-y-auto p-3 space-y-2">{logs.map((l, i) => (<div key={i} className="p-3 border-l-2 anim" style={{ background: "rgba(10,5,25,.5)", borderLeftColor: l.type === "success" ? "#22c55e" : l.type === "warning" ? "#eab308" : l.type === "error" ? "#ef4444" : l.type === "evidence" ? "#3b82f6" : "rgba(168,85,247,.4)" }}><div className="fm text-xs text-gray-500 mb-1">{l.time}</div><div className="text-xs text-gray-300 leading-relaxed">{l.message}</div>{l.scenario && <div className="fm text-xs text-purple-400 mt-1">{l.scenario}</div>}{l.actor && <div className="fm text-xs text-gray-600 mt-0.5">{l.actor}</div>}{l.detail && <div className="fm text-xs text-gray-600 mt-0.5">{l.detail}</div>}</div>))}{logs.length === 0 && <div className="text-center text-gray-600 fm text-xs py-8">NO_EVENTS</div>}</div></div>);

// ═══ LANDING PAGE ═══
const LandingPage = ({ onEnterApp }) => {
  const FAQ = ({ q, a }) => { const [open, setOpen] = useState(false); return (<div className="glass cursor-pointer" onClick={() => setOpen(!open)}><div className="p-6 fm text-purple-300 font-bold flex justify-between items-center text-sm">{q}<span className={`text-purple-500 transition-transform duration-300 ${open ? "rotate-180" : ""}`}>▼</span></div>{open && <div className="px-6 pb-6 text-gray-400 fm text-sm leading-relaxed border-t border-purple-500/10 pt-4 anim">{a}</div>}</div>); };
  return (
    <div className="min-h-screen">
      <nav className="fixed top-0 w-full z-50 p-4"><div className="max-w-7xl mx-auto glass rounded-sm flex justify-between items-center px-6 py-3"><div className="flex items-center gap-3"><span className="font-bold text-lg tracking-tight">QUANTUM_QUSTODY</span><span className="text-purple-500 fm" style={{ animation: "pulse 2s infinite" }}>_</span><Badge c="fuchsia">SANDBOX</Badge></div><div className="hidden md:flex gap-6 text-sm text-gray-400 fm"><a href="#technology" className="hover:text-purple-400 transition-colors">[ TECHNOLOGY ]</a><a href="#scenarios" className="hover:text-purple-400 transition-colors">[ SCENARIOS ]</a><a href="#pricing" className="hover:text-purple-400 transition-colors">[ PRICING ]</a></div><button onClick={onEnterApp} className="bg-purple-500/10 border border-purple-500/50 text-purple-400 px-4 py-2 text-sm fm hover:bg-purple-500/20 transition-all cursor-pointer">ACCESS SANDBOX</button></div></nav>

      <section className="pt-48 pb-24 px-4 flex flex-col items-center justify-center text-center relative">
        <div className="absolute inset-0 pointer-events-none" style={{ background: "radial-gradient(circle at center, rgba(168,85,247,.1) 0%, transparent 50%)" }} />
        <div className="glass px-4 py-1.5 rounded-full mb-8 fm text-xs text-purple-400 flex items-center gap-2 anim"><span className="w-2 h-2 rounded-full bg-purple-500" style={{ animation: "pulse 2s infinite" }} />MVP ALPHA SANDBOX</div>
        <h1 className="text-5xl md:text-7xl font-black tracking-tighter mb-6 leading-tight anim-d1">Institutional Control.<br /><span className="tg">Defensible Evidence.</span></h1>
        <p className="text-gray-400 text-lg md:text-xl max-w-2xl fm mb-10 leading-relaxed anim-d2">A new institutional operating model built around governed movement, policy enforcement, selective verification, and crypto-agile evidence.</p>
        <div className="flex flex-col sm:flex-row gap-4 anim-d3"><button onClick={onEnterApp} className="bg-gradient-to-r from-purple-600 to-fuchsia-600 text-white px-8 py-4 fm font-bold hover:from-purple-500 hover:to-fuchsia-500 transition-colors glow cursor-pointer">ENTER SANDBOX</button><button className="glass text-gray-300 px-8 py-4 fm hover:text-white transition-colors cursor-pointer">[ EVALUATION GUIDE ]</button></div>
      </section>

      <div className="w-full border-y border-purple-500/20 py-4 overflow-x-auto" style={{ background: "rgba(3,4,11,.8)" }}><div className="flex justify-center gap-8 md:gap-16 min-w-max px-8 max-w-7xl mx-auto fm text-sm md:text-base"><div className="flex gap-2"><span className="text-gray-500">[MODE]:</span><span className="text-fuchsia-400">SANDBOX</span></div><div className="flex gap-2"><span className="text-gray-500">[SCENARIOS]:</span><span className="text-white">5</span></div><div className="flex gap-2"><span className="text-gray-500">[PQC_VIEW]:</span><span className="text-purple-400">AVAILABLE</span></div><div className="flex gap-2"><span className="text-gray-500">[EVIDENCE]:</span><span className="text-emerald-400">STRUCTURED</span></div></div></div>

      <section id="technology" className="py-24 px-4 max-w-7xl mx-auto flex flex-col md:flex-row items-center gap-16">
        <div className="flex-1"><h2 className="text-sm fm text-fuchsia-500 tracking-widest mb-4">[ INSTITUTIONAL OPERATING MODEL ]</h2><h3 className="text-4xl font-bold mb-6">Beyond Custody.<br/>Governed Movement.</h3><p className="text-gray-400 fm mb-6 leading-relaxed">Quantum Qustody turns custody into an institution-controlled, policy-governed, evidence-rich, selectively verifiable, crypto-agile operating model.</p><ul className="space-y-4 fm text-sm text-gray-300"><li className="flex items-center gap-3"><span className="text-purple-500">▹</span> Policy-enforced movement with institutional accountability</li><li className="flex items-center gap-3"><span className="text-purple-500">▹</span> Oversight-ready evidence as a first-class output</li><li className="flex items-center gap-3"><span className="text-purple-500">▹</span> Selective verification without unnecessary disclosure</li><li className="flex items-center gap-3"><span className="text-purple-500">▹</span> PQC transition readiness at the operating-model level</li></ul></div>
        <div className="flex-1 flex justify-center py-12"><div className="relative w-64 h-64 flex items-center justify-center" style={{ perspective: "1000px" }}><div className="absolute w-full h-full border-2 border-purple-500/30 rounded-full orb1" style={{ boxShadow: "0 0 15px rgba(168,85,247,.2)" }} /><div className="absolute w-full h-full border-2 border-fuchsia-500/30 rounded-full orb2" style={{ boxShadow: "0 0 15px rgba(217,70,239,.2)" }} /><div className="absolute w-full h-full border-2 border-indigo-500/30 rounded-full orb3" style={{ boxShadow: "0 0 15px rgba(99,102,241,.2)" }} /><div className="w-12 h-12 bg-gradient-to-br from-purple-400 to-fuchsia-600 rounded-full" style={{ boxShadow: "0 0 30px #a855f7", animation: "pulse 2s infinite" }} /></div></div>
      </section>

      <section id="scenarios" className="py-24 px-4" style={{ background: "linear-gradient(to bottom, transparent, rgba(88,28,135,.08))" }}><div className="max-w-7xl mx-auto"><h2 className="text-center text-sm fm text-purple-500 tracking-widest mb-4">[ SANDBOX SCENARIOS ]</h2><h3 className="text-center text-3xl font-bold mb-12">Five Questions That Matter</h3><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">{SCENARIOS.map((s, i) => (<div key={s.id} className="glass p-6 hover:-translate-y-2 transition-transform duration-300" style={{ borderTop: `2px solid ${s.color === "purple" ? "rgba(168,85,247,.5)" : s.color === "fuchsia" ? "rgba(217,70,239,.5)" : "rgba(99,102,241,.5)"}` }}><div className="flex items-center gap-2 mb-3"><Badge c={s.tier === 1 ? "green" : "yellow"}>TIER {s.tier}</Badge><span className="fm text-xs text-gray-600">{s.num}</span></div><h4 className="font-bold text-sm mb-3">{s.title}</h4><p className="text-xs fm text-gray-400 leading-relaxed">{s.question}</p></div>))}</div></div></section>

      <section id="pricing" className="py-24 px-4 max-w-7xl mx-auto"><h2 className="text-center text-3xl font-bold mb-2">Engagement Path</h2><p className="text-center fm text-gray-500 mb-16 text-sm">SANDBOX → WORKSHOP → PILOT</p><div className="grid grid-cols-1 md:grid-cols-3 gap-8">
        <div className="glass p-8 flex flex-col" style={{ borderTop: "2px solid rgba(168,85,247,.5)" }}><h3 className="text-purple-400 fm mb-4">[ SANDBOX ]</h3><div className="text-2xl font-bold mb-6">Guided Evaluation</div><ul className="space-y-4 mb-8 text-gray-400 text-sm fm flex-grow"><li>✓ 5 Named Scenarios</li><li>✓ Structured Evidence</li><li>✓ Live + Simulated</li><li>✓ Self-Guided</li></ul><button onClick={onEnterApp} className="w-full py-3 bg-purple-600 text-white hover:bg-purple-500 fm font-bold transition-colors glow cursor-pointer">ENTER_SANDBOX</button></div>
        <div className="glass p-8 flex flex-col" style={{ borderTop: "2px solid rgba(217,70,239,.5)" }}><h3 className="text-fuchsia-400 fm mb-4">[ WORKSHOP ]</h3><div className="text-2xl font-bold mb-6">Institutional Deep-Dive</div><ul className="space-y-4 mb-8 text-gray-300 text-sm fm flex-grow"><li>✓ Custom Policy Mapping</li><li>✓ Evidence Review</li><li>✓ Integration Architecture</li><li>✓ Pilot Scoping</li></ul><button className="w-full py-3 border border-gray-600 text-gray-300 hover:bg-white hover:text-black fm transition-colors cursor-pointer">REQUEST_WORKSHOP</button></div>
        <div className="glass p-8 flex flex-col" style={{ borderTop: "2px solid rgba(99,102,241,.5)" }}><h3 className="text-indigo-400 fm mb-4">[ BOUNDED PILOT ]</h3><div className="text-2xl font-bold mb-6">Production Validation</div><ul className="space-y-4 mb-8 text-gray-400 text-sm fm flex-grow"><li>✓ Real Asset Boundaries</li><li>✓ Live Policy Enforcement</li><li>✓ Full Evidence</li><li>✓ Audit-Ready</li></ul><button className="w-full py-3 border border-gray-600 text-gray-300 hover:bg-white hover:text-black fm transition-colors cursor-pointer">DISCUSS_PILOT</button></div>
      </div></section>

      <section className="py-24 px-4 max-w-3xl mx-auto"><h2 className="text-2xl font-bold mb-8 text-center">Evaluation Questions</h2><div className="space-y-4">
        <FAQ q="What is the sandbox?" a="A bounded institutional evaluation environment demonstrating how Quantum Qustody governs movement, enforces policy, produces evidence, and supports selective verification and crypto-agility." />
        <FAQ q="What is live vs simulated?" a="Core governance workflows, policy application, and evidence generation are live. Cryptographic signing, on-chain execution, and certain PQC operations are simulated with realistic outputs." />
        <FAQ q="How does this lead to a workshop or pilot?" a="Each scenario triggers specific institutional questions. After evaluation, we map those to your context in a paid workshop, then validate with a bounded pilot." />
      </div></section>

      <footer className="border-t border-purple-500/20 bg-black py-12 px-6"><div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between items-center gap-4 fm text-xs text-gray-600"><div className="flex items-center gap-2"><span className="font-bold text-white text-sm">QUANTUM_QUSTODY</span><span className="text-purple-500">_</span><Badge c="fuchsia">SANDBOX</Badge></div><div>© 2026 QUANTUM QUSTODY. MVP ALPHA.</div></div></footer>
    </div>
  );
};

// ═══ SANDBOX SETUP ═══
const SandboxSetup = ({ onComplete, addLog }) => {
  const [step, setStep] = useState(0);
  const [form, setForm] = useState({ orgName: "", instType: "", jurisdiction: "", evalObjective: "", controlModel: "threshold", trustEnv: "current" });
  const u = (k, v) => setForm(p => ({ ...p, [k]: v }));
  const next = () => {
    const msgs = [{ type: "info", message: "Organization context configured", detail: `ENTITY: ${form.orgName || "—"}` },{ type: "info", message: "Roles & access configured", detail: "FUNCTIONS: 5" },{ type: "success", message: "Control posture configured", detail: `MODEL: ${form.controlModel.toUpperCase()}` }];
    if (step < 3) { addLog(msgs[step]); setStep(step + 1); } else { addLog({ type: "success", message: "Sandbox launched", detail: "EVALUATION_READY" }); onComplete(); }
  };
  const steps = [{ l: "CONTEXT", n: "01" }, { l: "ROLES", n: "02" }, { l: "POSTURE", n: "03" }, { l: "LAUNCH", n: "04" }];
  return (
    <div className="min-h-screen flex items-center justify-center p-6 relative"><div className="absolute inset-0 pointer-events-none" style={{ background: "radial-gradient(circle at center, rgba(168,85,247,.06) 0%, transparent 50%)" }} /><div className="w-full max-w-2xl anim"><div className="text-center mb-10"><div className="inline-flex items-center gap-2 mb-4"><span className="font-bold text-xl tracking-tight">QUANTUM_QUSTODY</span><span className="text-purple-500 fm" style={{ animation: "pulse 2s infinite" }}>_</span></div><h1 className="text-3xl font-bold mb-2">Sandbox Setup</h1><p className="fm text-sm text-gray-500">CONFIGURE YOUR EVALUATION ENVIRONMENT</p></div>
      <div className="flex items-center justify-center gap-1 mb-10">{steps.map((s, i) => (<div key={i} className="flex items-center"><div className={`flex items-center gap-2 px-3 py-1.5 fm text-xs transition-all duration-300 ${i === step ? "text-purple-400 bg-purple-500/10 border border-purple-500/30" : i < step ? "text-emerald-400" : "text-gray-600"}`}><span>{i < step ? "✓" : s.n}</span><span className="hidden sm:inline">{s.l}</span></div>{i < 3 && <div className={`w-8 h-px mx-1 ${i < step ? "bg-emerald-500/50" : "bg-gray-800"}`} />}</div>))}</div>
      <GC className="p-8">
        {step === 0 && <div className="space-y-5 anim" key="s0"><SL>ORGANIZATION CONTEXT</SL><div><label className="fm text-xs text-gray-500 mb-2 block">ORGANIZATION *</label><input placeholder="Institution name" value={form.orgName} onChange={e => u("orgName", e.target.value)} /></div><div className="grid grid-cols-2 gap-4"><div><label className="fm text-xs text-gray-500 mb-2 block">INSTITUTION_TYPE</label><select value={form.instType} onChange={e => u("instType", e.target.value)}><option value="">Select...</option><option>Asset Manager</option><option>Bank / Custodian</option><option>Fund</option><option>Corporate Treasury</option></select></div><div><label className="fm text-xs text-gray-500 mb-2 block">JURISDICTION</label><select value={form.jurisdiction} onChange={e => u("jurisdiction", e.target.value)}><option value="">Select...</option><option>United States</option><option>European Union</option><option>United Kingdom</option><option>Singapore</option></select></div></div><div><label className="fm text-xs text-gray-500 mb-2 block">EVALUATION_OBJECTIVE</label><input placeholder="e.g., Assess governed treasury controls" value={form.evalObjective} onChange={e => u("evalObjective", e.target.value)} /></div></div>}
        {step === 1 && <div className="space-y-5 anim" key="s1"><SL>ROLES & ACCESS</SL><p className="fm text-xs text-gray-400 mb-4">Pre-configured institutional governance functions:</p><div className="space-y-2">{PARTICIPANTS.map(p => (<div key={p.id} className="flex items-center justify-between p-3 bg-black/30 border border-gray-800/50"><div className="flex items-center gap-3"><div className="w-8 h-8 rounded-full bg-gradient-to-br from-purple-500 to-fuchsia-600 flex items-center justify-center text-xs font-bold">{p.initials}</div><div><div className="text-sm font-bold">{p.name}</div><div className="fm text-xs text-gray-500">{p.fn}</div></div></div><Badge c="purple">{p.role.toUpperCase()}</Badge></div>))}</div></div>}
        {step === 2 && <div className="space-y-5 anim" key="s2"><SL>CONTROL POSTURE</SL><div><label className="fm text-xs text-gray-500 mb-3 block">CONTROL_MODEL</label><div className="grid grid-cols-3 gap-3">{[{ id: "single", l: "Single Authority", d: "One approver" }, { id: "threshold", l: "Threshold", d: "Multi-approval" }, { id: "committee", l: "Committee", d: "Full governance" }].map(o => (<div key={o.id} onClick={() => u("controlModel", o.id)} className={`p-4 cursor-pointer border transition-all ${form.controlModel === o.id ? "border-purple-500 bg-purple-500/10 text-white" : "border-gray-800 bg-gray-900/30 text-gray-500 hover:border-gray-700"}`}><div className="fm text-sm font-bold mb-1">{o.l}</div><div className="text-xs">{o.d}</div></div>))}</div></div><div><label className="fm text-xs text-gray-500 mb-3 block">TRUST_ENVIRONMENT</label><div className="grid grid-cols-2 gap-3">{[{ id: "current", l: "Current Trust Basis", d: "Standard cryptographic" }, { id: "pqc", l: "PQC Target Posture", d: "Post-quantum view" }].map(o => (<div key={o.id} onClick={() => u("trustEnv", o.id)} className={`p-4 cursor-pointer border transition-all ${form.trustEnv === o.id ? "border-fuchsia-500 bg-fuchsia-500/10 text-white" : "border-gray-800 bg-gray-900/30 text-gray-500 hover:border-gray-700"}`}><div className="fm text-sm font-bold mb-1">{o.l}</div><div className="text-xs">{o.d}</div></div>))}</div></div></div>}
        {step === 3 && <div className="space-y-5 anim" key="s3"><SL>LAUNCH SANDBOX</SL><div className="text-center py-4"><div className="inline-block p-4 rounded-full bg-purple-500/10 border border-purple-500/30 mb-4"><IC.Shield /></div><h3 className="text-xl font-bold mb-2">Sandbox Ready</h3><p className="fm text-sm text-gray-500">You will be directed to the Evaluation Hub.</p></div><div className="space-y-2 p-4 bg-black/40 border border-gray-800 fm text-xs"><div className="flex justify-between"><span className="text-gray-500">ORG:</span><span>{form.orgName || "—"}</span></div><div className="flex justify-between"><span className="text-gray-500">CONTROL:</span><span className="text-purple-400">{form.controlModel.toUpperCase()}</span></div><div className="flex justify-between"><span className="text-gray-500">TRUST:</span><span className="text-fuchsia-400">{form.trustEnv === "pqc" ? "PQC TARGET" : "CURRENT"}</span></div><div className="flex justify-between"><span className="text-gray-500">SCENARIOS:</span><span className="text-emerald-400">5 AVAILABLE</span></div></div><div className="p-4 bg-purple-500/5 border border-purple-500/20 fm text-xs text-gray-400 space-y-1"><div className="flex gap-2"><span className="text-emerald-400">●</span> Live: Governance, policy, evidence</div><div className="flex gap-2"><span className="text-yellow-400">●</span> Simulated: Signing, settlement</div><div className="flex gap-2"><span className="text-blue-400">●</span> Workshop: Custom policy, integration</div><div className="flex gap-2"><span className="text-gray-500">●</span> Roadmap: Full PQC, production HSM</div></div></div>}
        <div className="flex justify-between mt-8 pt-6 border-t border-purple-500/10"><Btn v="ghost" onClick={() => step > 0 && setStep(step - 1)} disabled={step === 0}>BACK</Btn><Btn onClick={next}>{step === 3 ? "LAUNCH_SANDBOX" : "CONTINUE"} <IC.Arrow /></Btn></div>
      </GC></div></div>
  );
};

// ═══ SIDEBAR ═══
const SideNav = ({ active, setActive, onLogout }) => {
  const nav = [{ id: "hub", l: "EVALUATION HUB", i: <IC.Hub /> },{ id: "overview", l: "EVAL OVERVIEW", i: <IC.Scenario /> },{ id: "assets", l: "ASSET BOUNDARY", i: <IC.Asset /> },{ id: "movement", l: "GOVERNED MOVEMENT", i: <IC.Move /> },{ id: "participants", l: "PARTICIPANTS", i: <IC.People /> },{ id: "evidence", l: "EVIDENCE VIEWER", i: <IC.Evidence /> },{ id: "config", l: "EVAL CONFIG", i: <IC.Config /> }];
  return (<div className="w-56 flex-shrink-0 border-r border-purple-500/20 flex flex-col" style={{ height: "calc(100vh - 56px)", background: "rgba(5,2,15,.5)" }}><div className="p-4 space-y-1 flex-1">{nav.map(n => <button key={n.id} onClick={() => setActive(n.id)} className={`w-full flex items-center gap-3 px-3 py-2.5 fm text-xs transition-all cursor-pointer ${active === n.id ? "text-purple-400 bg-purple-500/10 border-l-2 border-purple-500" : "text-gray-500 hover:text-gray-300 hover:bg-white/5 border-l-2 border-transparent"}`}>{n.i}{n.l}</button>)}</div><div className="p-4 border-t border-purple-500/10"><button onClick={onLogout} className="w-full fm text-xs text-gray-600 hover:text-red-400 transition-colors cursor-pointer text-left px-1 py-1">← EXIT_SANDBOX</button></div></div>);
};

// ═══ EVALUATION HUB ═══
const EvaluationHub = ({ setView, setScenario, addLog }) => {
  const start = (s) => { addLog({ type: "info", message: `Scenario detail loaded: ${s.title}`, scenario: `SCENARIO ${s.num}` }); setScenario(s); setView("scenario-detail"); };
  return (<div className="p-6 space-y-6 overflow-y-auto flex-1">
    <div className="anim"><h2 className="text-2xl font-bold mb-1">Evaluation Hub</h2><p className="fm text-sm text-gray-500">YOUR SANDBOX IS CONFIGURED AND READY FOR GUIDED EVALUATION</p></div>
    <GC className="p-5 anim-d1"><SL>ENVIRONMENT SUMMARY</SL><div className="grid grid-cols-2 md:grid-cols-4 gap-4"><div><div className="fm text-xs text-gray-500 mb-1">ORGANIZATION</div><div className="text-sm font-bold">Acme Capital</div></div><div><div className="fm text-xs text-gray-500 mb-1">INSTITUTION TYPE</div><div className="text-sm font-bold">Asset Manager</div></div><div><div className="fm text-xs text-gray-500 mb-1">CONTROL MODEL</div><div className="text-sm font-bold text-purple-400">Threshold</div></div><div><div className="fm text-xs text-gray-500 mb-1">TRUST ENVIRONMENT</div><div className="text-sm font-bold text-fuchsia-400">Current + PQC</div></div></div></GC>
    <GC className="p-5 anim-d2" style={{ borderTop: "2px solid rgba(168,85,247,.4)" }}><div className="flex items-center gap-2 mb-3"><Badge c="green">RECOMMENDED</Badge></div><h3 className="font-bold text-lg mb-2">{SCENARIOS[0].title}</h3><p className="fm text-xs text-gray-400 mb-3">{SCENARIOS[0].question}</p><div className="flex flex-wrap gap-2 mb-4">{SCENARIOS[0].evidence.map((e, i) => <Badge key={i} c="purple">{e}</Badge>)}</div><Btn onClick={() => start(SCENARIOS[0])}>START_RECOMMENDED_SCENARIO <IC.Arrow /></Btn></GC>
    <SL>ALL SCENARIOS</SL>
    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">{SCENARIOS.map((s, i) => (<GC key={s.id} hover className={`p-5 anim-d${Math.min(i,3)+1}`} style={{ borderLeft: `3px solid ${s.color==="purple"?"#a855f7":s.color==="fuchsia"?"#d946ef":"#818cf8"}` }} onClick={() => start(s)}><div className="flex items-center gap-2 mb-2"><Badge c={s.tier===1?"green":"yellow"}>TIER {s.tier}</Badge><span className="fm text-xs text-gray-600">{s.num}</span></div><h4 className="font-bold text-sm mb-2">{s.title}</h4><p className="fm text-xs text-gray-500 leading-relaxed mb-3">{s.question}</p><div className="fm text-xs text-gray-600">Uses: {s.screens.join(" → ")}</div></GC>))}
      <GC hover className="p-5 anim-d4" style={{ borderLeft: "3px solid rgba(107,114,128,.3)" }} onClick={() => { addLog({ type: "info", message: "General exploration mode" }); setView("overview"); }}><Badge c="yellow">OPTIONAL</Badge><h4 className="font-bold text-sm mt-2 mb-2">General Platform Exploration</h4><p className="fm text-xs text-gray-500">Navigate freely. Not recommended for first evaluation.</p></GC>
    </div>
    <GC className="p-5 anim-d4"><SL>STAGE HONESTY</SL><div className="grid grid-cols-2 md:grid-cols-4 gap-4 fm text-xs"><div><div className="flex items-center gap-2 mb-2"><span className="w-2 h-2 rounded-full bg-emerald-400" /><span className="text-emerald-400">Live</span></div><div className="text-gray-500">Governance, policy, evidence, audit</div></div><div><div className="flex items-center gap-2 mb-2"><span className="w-2 h-2 rounded-full bg-yellow-400" /><span className="text-yellow-400">Simulated</span></div><div className="text-gray-500">Signing, settlement, on-chain</div></div><div><div className="flex items-center gap-2 mb-2"><span className="w-2 h-2 rounded-full bg-blue-400" /><span className="text-blue-400">Workshop</span></div><div className="text-gray-500">Custom policy, integration</div></div><div><div className="flex items-center gap-2 mb-2"><span className="w-2 h-2 rounded-full bg-gray-500" /><span className="text-gray-400">Roadmap</span></div><div className="text-gray-500">Full PQC, production HSM</div></div></div></GC>
  </div>);
};

// ═══ SCENARIO DETAIL ═══
const ScenarioDetail = ({ scenario, setView, addLog }) => { if (!scenario) return null; const begin = () => { addLog({ type: "info", message: `Scenario started`, scenario: `SCENARIO ${scenario.num}` }); setView(scenario.id==="s1"?"assets":scenario.id==="s2"?"movement":"evidence"); }; return (<div className="p-6 space-y-6 overflow-y-auto flex-1"><div className="flex items-center gap-3 mb-2"><Btn v="ghost" onClick={() => setView("hub")}><IC.Back /> HUB</Btn></div><div className="anim"><div className="flex items-center gap-3 mb-2"><Badge c={scenario.tier===1?"green":"yellow"}>TIER {scenario.tier}</Badge><Badge c="purple">SCENARIO {scenario.num}</Badge></div><h2 className="text-2xl font-bold mb-2">{scenario.title}</h2><p className="fm text-sm text-gray-400 max-w-2xl">{scenario.question}</p></div><div className="grid grid-cols-1 md:grid-cols-2 gap-6"><GC className="p-5 anim-d1"><SL>WHAT YOU WILL DO</SL><p className="fm text-xs text-gray-400 leading-relaxed">{scenario.demo}</p></GC><GC className="p-5 anim-d2"><SL>SCREENS USED</SL><div className="space-y-2">{scenario.screens.map((s,i) => <div key={i} className="flex items-center gap-2 fm text-xs text-gray-300"><span className="text-purple-500">{String(i+1).padStart(2,"0")}</span>{s}</div>)}</div></GC></div><GC className="p-5 anim-d2"><SL>EVIDENCE TO BE PRODUCED</SL><div className="flex flex-wrap gap-2">{scenario.evidence.map((e,i) => <Badge key={i} c="blue">{e}</Badge>)}</div></GC><GC className="p-5 anim-d3"><SL>WORKSHOP QUESTION</SL><p className="fm text-xs text-gray-400 leading-relaxed italic">How would this governance model map to your specific institutional policy framework, approval authorities, and evidence requirements?</p></GC><div className="flex gap-3 anim-d4"><Btn onClick={begin}>BEGIN_SCENARIO <IC.Arrow /></Btn><Btn v="secondary" onClick={() => setView("hub")}>RETURN_TO_HUB</Btn></div></div>); };

// ═══ EVAL OVERVIEW ═══
const EvalOverview = ({ activeScenario, setView, addLog }) => (<div className="p-6 space-y-6 overflow-y-auto flex-1"><div><h2 className="text-2xl font-bold mb-1 anim">Evaluation Overview</h2><p className="fm text-sm text-gray-500 anim-d1">ACTIVE SANDBOX EVALUATION</p></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4"><GC className="p-5 anim"><div className="fm text-xs text-gray-500 mb-2">[ ACTIVE_SCENARIO ]</div><div className="text-lg font-bold mb-1">{activeScenario?activeScenario.num:"None"}</div><div className="fm text-xs text-gray-500">{activeScenario?activeScenario.title.split(" ").slice(0,4).join(" ")+"...":"Select from Hub"}</div></GC><GC className="p-5 anim-d1"><div className="fm text-xs text-gray-500 mb-2">[ CONTROL_MODEL ]</div><div className="text-lg font-bold mb-1">Threshold</div><div className="fm text-xs text-gray-500">Multi-approval</div></GC><GC className="p-5 anim-d2"><div className="fm text-xs text-gray-500 mb-2">[ EVIDENCE ]</div><div className="text-lg font-bold mb-1 text-emerald-400">Available</div><div className="fm text-xs text-gray-500">Structured outputs</div></GC><GC className="p-5 anim-d3"><div className="fm text-xs text-gray-500 mb-2">[ TRUST ]</div><div className="text-lg font-bold mb-1 text-fuchsia-400">Current + PQC</div><div className="fm text-xs text-gray-500">Crypto-agility view</div></GC></div>{activeScenario && <GC className="p-5 anim-d2" style={{ borderLeft: "3px solid #a855f7" }}><div className="flex items-center justify-between"><div><SL>ACTIVE SCENARIO</SL><h3 className="font-bold">{activeScenario.title}</h3></div><Btn onClick={() => setView("scenario-detail")}>CONTINUE <IC.Arrow /></Btn></div></GC>}<div className="flex gap-3 anim-d3"><Btn v="secondary" onClick={() => setView("evidence")}>VIEW_EVIDENCE</Btn><Btn v="secondary" onClick={() => setView("hub")}>RETURN_TO_HUB</Btn></div></div>);

// ═══ ASSET BOUNDARY ═══
const AssetBoundary = ({ addLog, setView }) => (<div className="p-6 space-y-6 overflow-y-auto flex-1"><div className="flex items-center justify-between"><div><h2 className="text-2xl font-bold mb-1">Asset Boundary</h2><p className="fm text-sm text-gray-500">IN-SCOPE ASSETS FOR CURRENT EVALUATION</p></div><Btn onClick={() => addLog({ type: "info", message: "Add in-scope asset initiated" })}>ADD_IN_SCOPE_ASSET</Btn></div><div className="space-y-3">{ASSETS.map((a,i) => (<GC key={a.id} hover className={`p-5 flex items-center justify-between anim-d${Math.min(i,3)+1}`} onClick={() => { addLog({ type: "info", message: `Asset selected: ${a.name}`, detail: `BOUNDARY: ${a.boundary}` }); setView("movement"); }}><div className="flex items-center gap-4"><div className={`w-10 h-10 rounded-full flex items-center justify-center fm text-xs font-bold ${a.scope?"bg-gradient-to-br from-purple-500/30 to-fuchsia-500/30 text-purple-300":"bg-gray-800/50 text-gray-500"}`}>{a.chain.slice(0,3).toUpperCase()}</div><div><div className="font-bold">{a.name}</div><div className="fm text-xs text-gray-500">{a.chain} · {a.control}</div></div></div><div className="flex items-center gap-4"><div className="text-right"><div className="fm text-sm font-bold">{a.balance}</div><div className="fm text-xs text-gray-500">{a.usd}</div></div><Badge c={a.scope?"green":"yellow"}>{a.scope?"IN-SCOPE":"OUT-OF-SCOPE"}</Badge><Badge c="purple">{a.boundary.toUpperCase()}</Badge></div></GC>))}</div></div>);

// ═══ GOVERNED MOVEMENT ═══
const GovernedMovement = ({ activeScenario, addLog, setView }) => {
  const [step, setMoveStep] = useState("request");
  const [fd, setFd] = useState({ from: "", amount: "", asset: "ETH" });
  const up = (k,v) => setFd(p => ({...p,[k]:v}));
  const advance = (next, msg, type="info") => { addLog({ type, message: msg, scenario: activeScenario?`SCENARIO ${activeScenario.num}`:undefined, actor: step==="request"?"Treasury / Operations":step==="policy"?"System":"Risk Management" }); setMoveStep(next); };
  const isBlocked = activeScenario?.id === "s2";
  return (<div className="p-6 space-y-6 overflow-y-auto flex-1"><div><h2 className="text-2xl font-bold mb-1">Governed Movement</h2><p className="fm text-sm text-gray-500">REQUEST → GOVERNANCE → EXECUTION</p></div>
    {activeScenario && <GC className="p-4 anim" style={{ borderLeft: "3px solid #a855f7" }}><div className="flex items-center gap-3 fm text-xs"><Badge c="purple">SCENARIO {activeScenario.num}</Badge><span className="text-gray-400">{activeScenario.title}</span><span className="text-gray-600">|</span><span className="text-purple-400 font-bold">{step.toUpperCase()}</span></div></GC>}
    <div className="flex gap-2 anim-d1">{["request","policy","approval","execution"].map((s,i) => (<div key={s} className={`flex items-center gap-1 px-3 py-1.5 fm text-xs ${step===s?"text-purple-400 bg-purple-500/10 border border-purple-500/30":i<["request","policy","approval","execution"].indexOf(step)?"text-emerald-400":"text-gray-600"}`}>{i<["request","policy","approval","execution"].indexOf(step)?"✓":String(i+1).padStart(2,"0")} {s.toUpperCase()}</div>))}</div>
    {step==="request" && <GC className="p-6 anim max-w-xl"><SL>SUBMIT REQUEST</SL><div className="space-y-5"><div><label className="fm text-xs text-gray-500 mb-2 block">FROM_ASSET</label><select value={fd.from} onChange={e=>up("from",e.target.value)}><option value="">Select in-scope asset...</option>{ASSETS.filter(a=>a.scope).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></div><div className="grid grid-cols-2 gap-4"><div><label className="fm text-xs text-gray-500 mb-2 block">AMOUNT</label><input type="number" placeholder="0.00" value={fd.amount} onChange={e=>up("amount",e.target.value)}/></div><div><label className="fm text-xs text-gray-500 mb-2 block">ASSET</label><select value={fd.asset} onChange={e=>up("asset",e.target.value)}><option>ETH</option><option>BTC</option><option>USDC</option></select></div></div><Btn full onClick={()=>advance("policy",`Request created: ${fd.amount||"0"} ${fd.asset}`)}>SUBMIT_REQUEST <IC.Arrow /></Btn></div></GC>}
    {step==="policy" && <GC className="p-6 anim max-w-xl"><SL>POLICY APPLICATION</SL><div className="space-y-4"><InfoRow label="POLICY_IN_FORCE" value="Treasury Movement Policy v2.1" /><InfoRow label="THRESHOLD" value={isBlocked?"Exceeded — $500K limit":"Within bounds"} /><InfoRow label="DESTINATION" value={isBlocked?"Restricted — unlisted":"Approved counterparty"} /><InfoRow label="OUTCOME" badge={isBlocked?{t:"BLOCKED",c:"red"}:{t:"PASSED",c:"green"}} />{isBlocked && <div className="p-4 bg-red-500/5 border border-red-500/20 fm text-xs text-red-300">Policy conflict detected. Movement blocked.</div>}<Btn full onClick={()=>advance(isBlocked?"execution":"approval",isBlocked?"Policy BLOCKED":"Policy passed",isBlocked?"error":"info")}>{isBlocked?"VIEW_EXCEPTION":"VIEW_POLICY_PATH"} <IC.Arrow /></Btn></div></GC>}
    {step==="approval" && <GC className="p-6 anim max-w-xl"><SL>THRESHOLD APPROVAL</SL><div className="space-y-4">{PARTICIPANTS.filter(p=>["Approver","Reviewer"].includes(p.role)).map(p=>(<div key={p.id} className="flex items-center justify-between p-3 bg-black/30 border border-gray-800/50"><div className="flex items-center gap-3"><div className="w-8 h-8 rounded-full bg-gradient-to-br from-purple-500 to-fuchsia-600 flex items-center justify-center text-xs font-bold">{p.initials}</div><div><div className="text-sm font-bold">{p.name}</div><div className="fm text-xs text-gray-500">{p.fn}</div></div></div><Badge c="green">APPROVED</Badge></div>))}<InfoRow label="THRESHOLD" value="2 of 2 — Met" /><Btn full onClick={()=>advance("execution","Approval complete","success")}>ADVANCE_TO_EXECUTION <IC.Arrow /></Btn></div></GC>}
    {step==="execution" && <GC className="p-6 anim max-w-xl"><SL>{isBlocked?"BLOCKED OUTCOME":"EXECUTION COMPLETE"}</SL><div className="space-y-4"><div className="text-center py-4"><div className={`inline-block p-4 rounded-full mb-4 ${isBlocked?"bg-red-500/10 border border-red-500/30":"bg-emerald-500/10 border border-emerald-500/30"}`}>{isBlocked?<IC.Block />:<IC.Check />}</div><h3 className="text-xl font-bold mb-2">{isBlocked?"Movement Blocked":"Movement Executed"}</h3><p className="fm text-sm text-gray-500">{isBlocked?"Exception evidence generated.":"Full evidence trail generated."}</p></div><div className="flex gap-3"><Btn onClick={()=>{addLog({type:"evidence",message:"Evidence generated",scenario:activeScenario?`SCENARIO ${activeScenario.num}`:undefined});setView("evidence")}}>VIEW_EVIDENCE <IC.Arrow /></Btn><Btn v="secondary" onClick={()=>setView("scenario-complete")}>COMPLETE_SCENARIO</Btn></div></div></GC>}
  </div>);
};

// ═══ GOVERNANCE PARTICIPANTS ═══
const GovParticipants = ({ addLog }) => (<div className="p-6 space-y-6 overflow-y-auto flex-1"><div className="flex items-center justify-between"><div><h2 className="text-2xl font-bold mb-1">Governance Participants</h2><p className="fm text-sm text-gray-500">FUNCTIONS · AUTHORITY · OVERSIGHT</p></div><Btn onClick={()=>addLog({type:"info",message:"Add participant initiated"})}>ADD_PARTICIPANT</Btn></div><div className="space-y-3">{PARTICIPANTS.map((p,i)=>(<GC key={p.id} hover className={`p-5 flex items-center justify-between anim-d${Math.min(i,3)+1}`}><div className="flex items-center gap-4"><div className="w-10 h-10 rounded-full bg-gradient-to-br from-purple-500 to-fuchsia-600 flex items-center justify-center font-bold text-sm">{p.initials}</div><div><div className="font-bold">{p.name}</div><div className="fm text-xs text-gray-500">{p.fn}</div></div></div><div className="flex items-center gap-3"><Badge c="purple">{p.role.toUpperCase()}</Badge><Badge c={p.status==="active"?"green":"yellow"}>{p.status.toUpperCase()}</Badge></div></GC>))}</div></div>);

// ═══ EVIDENCE VIEWER ═══
const EvidenceViewer = ({ activeScenario, addLog, setView }) => {
  const [activeTab, setActiveTab] = useState("policy");
  const tabs = activeScenario?.id==="s4"?[{id:"full",l:"Full Evidence"},{id:"selective",l:"Selective Verification"},{id:"disclosure",l:"Disclosure Boundary"}]:activeScenario?.id==="s5"?[{id:"profile",l:"Crypto Assurance"},{id:"current-pqc",l:"Current vs PQC"},{id:"continuity",l:"Migration Continuity"}]:[{id:"policy",l:"Policy Trace"},{id:"approval",l:"Approval Chain"},{id:"control",l:"Control Record"},{id:"outcome",l:"Outcome"},{id:"oversight",l:"Oversight Summary"}];
  return (<div className="p-6 space-y-6 overflow-y-auto flex-1"><div className="flex items-center justify-between"><div><h2 className="text-2xl font-bold mb-1">Evidence Viewer</h2><p className="fm text-sm text-gray-500">INSTITUTIONALLY LEGIBLE EVIDENCE</p></div><Btn v="secondary" onClick={()=>addLog({type:"evidence",message:"Evidence PDF downloaded"})}><IC.Download /> DOWNLOAD_PDF</Btn></div>
    {activeScenario && <GC className="p-4 anim" style={{ borderLeft: "3px solid #3b82f6" }}><div className="flex items-center gap-3 fm text-xs"><Badge c="blue">EVIDENCE</Badge><span className="text-gray-400">Scenario {activeScenario.num}</span></div></GC>}
    <div className="flex gap-2 flex-wrap anim-d1">{tabs.map(t=>(<button key={t.id} onClick={()=>{setActiveTab(t.id);addLog({type:"info",message:`Evidence: ${t.l}`});}} className={`px-4 py-2 fm text-xs cursor-pointer transition-all ${activeTab===t.id?"text-purple-400 bg-purple-500/10 border border-purple-500/40":"text-gray-500 hover:text-gray-300 border border-transparent"}`}>{t.l}</button>))}</div>
    <GC className="p-6 anim-d2"><SL>{tabs.find(t=>t.id===activeTab)?.l.toUpperCase()||"EVIDENCE"}</SL>
      {(activeTab==="policy"||activeTab==="full"||activeTab==="profile") && <div className="space-y-3"><InfoRow label="POLICY_REFERENCE" value="Treasury Movement Policy v2.1" /><InfoRow label="APPLICABLE_RULES" value="Threshold, destination whitelist, amount ceiling" /><InfoRow label="POLICY_EVALUATION" badge={{t:"EVALUATED",c:"green"}} /><InfoRow label="EXCEPTION" badge={{t:activeScenario?.id==="s2"?"YES":"NONE",c:activeScenario?.id==="s2"?"red":"green"}} />{activeTab==="profile"&&<><InfoRow label="CURRENT_BASIS" value="ECDSA / Ed25519" /><InfoRow label="PQC_TARGET" value="ML-KEM-768 / ML-DSA-65" /><InfoRow label="CONTINUITY" badge={{t:"MAINTAINED",c:"green"}} /></>}</div>}
      {(activeTab==="approval"||activeTab==="selective") && <div className="space-y-3"><InfoRow label="MODEL" value="Threshold: 2 of 2" />{PARTICIPANTS.filter(p=>["Approver","Reviewer"].includes(p.role)).map(p=><InfoRow key={p.id} label={p.fn.toUpperCase()} value={`${p.name} — ${p.role}`} />)}<InfoRow label="STATUS" badge={{t:"COMPLETE",c:"green"}} />{activeTab==="selective"&&<><div className="mt-4 p-4 bg-purple-500/5 border border-purple-500/20 fm text-xs text-gray-400"><span className="text-purple-400">SELECTIVE VERIFICATION:</span> Conditions verified without exposing underlying data:</div><InfoRow label="GOVERNANCE" badge={{t:"VERIFIED ✓",c:"green"}} /><InfoRow label="THRESHOLD" badge={{t:"VERIFIED ✓",c:"green"}} /><InfoRow label="UNDERLYING_DATA" badge={{t:"PROTECTED",c:"purple"}} /></>}</div>}
      {(activeTab==="control"||activeTab==="disclosure") && <div className="space-y-3"><InfoRow label="CONTROL_TYPE" value="Multi-approval threshold" /><InfoRow label="APPLIED" badge={{t:"YES",c:"green"}} /><InfoRow label="OUTCOME" badge={{t:activeScenario?.id==="s2"?"BLOCKED":"PASSED",c:activeScenario?.id==="s2"?"red":"green"}} />{activeTab==="disclosure"&&<><div className="mt-4 p-4 bg-indigo-500/5 border border-indigo-500/20 fm text-xs text-gray-400"><span className="text-indigo-400">DISCLOSURE BOUNDARY:</span></div><InfoRow label="DISCLOSED" value="Governance outcome, compliance status" /><InfoRow label="PROTECTED" value="Balances, addresses, internal policies" /></>}</div>}
      {(activeTab==="outcome"||activeTab==="current-pqc") && <div className="space-y-3"><InfoRow label="REQUEST_ID" value="QQ-TXN-2026-0847" /><InfoRow label="STATUS" badge={{t:activeScenario?.id==="s2"?"BLOCKED":"EXECUTED",c:activeScenario?.id==="s2"?"red":"green"}} /><InfoRow label="TIMESTAMP" value="2026-03-11T10:47:22Z" />{activeTab==="current-pqc"&&<><div className="mt-4 grid grid-cols-2 gap-4"><div className="p-4 bg-black/30 border border-gray-800"><div className="fm text-xs text-gray-500 mb-2">CURRENT</div><InfoRow label="SIGNING" value="ECDSA P-256" /><InfoRow label="VERIFY" value="Ed25519" /></div><div className="p-4 bg-purple-500/5 border border-purple-500/20"><div className="fm text-xs text-purple-400 mb-2">PQC TARGET</div><InfoRow label="SIGNING" value="ML-DSA-65" /><InfoRow label="VERIFY" value="ML-DSA-65" /></div></div><InfoRow label="POLICY_CHANGE" badge={{t:"NONE REQUIRED",c:"green"}} /></>}</div>}
      {(activeTab==="oversight"||activeTab==="continuity") && <div className="space-y-3"><InfoRow label="RECIPIENTS" value="Risk, Audit, Compliance, Finance" /><InfoRow label="COMPLETENESS" badge={{t:"COMPLETE",c:"green"}} />{activeTab==="continuity"&&<><InfoRow label="POLICY_CONTINUITY" badge={{t:"MAINTAINED",c:"green"}} /><InfoRow label="APPROVAL_CONTINUITY" badge={{t:"MAINTAINED",c:"green"}} /><InfoRow label="EVIDENCE_CONTINUITY" badge={{t:"MAINTAINED",c:"green"}} /></>}</div>}
    </GC>
    <div className="flex gap-3 anim-d3"><Btn v="secondary" onClick={()=>setView("scenario-complete")}>COMPLETE_SCENARIO</Btn><Btn v="ghost" onClick={()=>setView("hub")}>RETURN_TO_HUB</Btn></div>
  </div>);
};

// ═══ SCENARIO COMPLETION ═══
const ScenarioComplete = ({ activeScenario, setView, setScenario, addLog }) => {
  if (!activeScenario) return null;
  const nextIdx = SCENARIOS.findIndex(s=>s.id===activeScenario.id)+1;
  const next = nextIdx < SCENARIOS.length ? SCENARIOS[nextIdx] : null;
  return (<div className="p-6 space-y-6 overflow-y-auto flex-1"><div className="text-center py-6 anim"><div className="inline-block p-4 rounded-full bg-emerald-500/10 border border-emerald-500/30 mb-4"><IC.Check /></div><h2 className="text-2xl font-bold mb-2">Scenario Complete</h2><p className="fm text-sm text-gray-500">{activeScenario.title}</p></div>
    <GC className="p-5 anim-d1"><SL>DEMONSTRATED</SL><p className="fm text-xs text-gray-400 leading-relaxed">{activeScenario.demo}</p></GC>
    <GC className="p-5 anim-d2"><SL>EVIDENCE GENERATED</SL><div className="flex flex-wrap gap-2">{activeScenario.evidence.map((e,i)=><Badge key={i} c="blue">{e}</Badge>)}</div></GC>
    <GC className="p-5 anim-d3"><SL>WORKSHOP FOCUS</SL><p className="fm text-xs text-gray-400">Map this governance model to your institutional context: policy framework, approval authorities, evidence requirements.</p></GC>
    {next && <GC className="p-5 anim-d3" style={{ borderTop: "2px solid rgba(168,85,247,.4)" }}><Badge c="purple">NEXT</Badge><h3 className="font-bold mt-2 mb-1">{next.title}</h3><p className="fm text-xs text-gray-500 mb-3">{next.question}</p><Btn onClick={()=>{addLog({type:"info",message:`Next: ${next.title}`,scenario:`SCENARIO ${next.num}`});setScenario(next);setView("scenario-detail")}}>CONTINUE_TO_NEXT <IC.Arrow /></Btn></GC>}
    <div className="flex gap-3 anim-d4"><Btn v="secondary" onClick={()=>setView("evidence")}>VIEW_EVIDENCE</Btn><Btn v="secondary" onClick={()=>setView("hub")}>RETURN_TO_HUB</Btn></div>
  </div>);
};

// ═══ EVAL CONFIG ═══
const EvalConfig = ({ addLog }) => {
  const [tab, setTab] = useState("context");
  return (<div className="p-6 space-y-6 overflow-y-auto flex-1"><div><h2 className="text-2xl font-bold mb-1">Evaluation Configuration</h2><p className="fm text-sm text-gray-500">CONTEXT · CONTROL POSTURE · EVIDENCE & ASSURANCE</p></div>
    <div className="flex gap-2">{[{id:"context",l:"Context"},{id:"control",l:"Control Posture"},{id:"evidence",l:"Evidence & Assurance"}].map(t=>(<button key={t.id} onClick={()=>setTab(t.id)} className={`px-4 py-2 fm text-xs cursor-pointer transition-all ${tab===t.id?"text-purple-400 bg-purple-500/10 border border-purple-500/40":"text-gray-500 hover:text-gray-300 border border-transparent"}`}>{t.l}</button>))}</div>
    {tab==="context" && <GC className="p-6 anim"><SL>ORGANIZATION</SL><div className="space-y-3"><InfoRow label="ORGANIZATION" value="Acme Capital" /><InfoRow label="TYPE" value="Asset Manager" /><InfoRow label="JURISDICTION" value="European Union" /><InfoRow label="OBJECTIVE" value="Assess governed treasury controls" /></div></GC>}
    {tab==="control" && <GC className="p-6 anim"><SL>CONTROL POSTURE</SL><div className="space-y-3"><InfoRow label="CONTROL_MODEL" value="Threshold Governance" /><InfoRow label="TRUST" value="Current + PQC Target" /><InfoRow label="BOUNDARIES" value="4 in-scope, 1 out-of-scope" /><InfoRow label="ROLE_SEPARATION" value="5 functions configured" /></div></GC>}
    {tab==="evidence" && <GC className="p-6 anim"><SL>EVIDENCE & ASSURANCE</SL><div className="space-y-3"><InfoRow label="EVIDENCE_VIEWS" badge={{t:"AVAILABLE",c:"green"}} /><InfoRow label="SELECTIVE_VERIFICATION" badge={{t:"VIEW AVAILABLE",c:"fuchsia"}} /><InfoRow label="PQC_CRYPTO_AGILITY" badge={{t:"VIEW AVAILABLE",c:"purple"}} /></div><div className="mt-4 p-4 bg-purple-500/5 border border-purple-500/20 fm text-xs text-gray-400 space-y-1"><div className="flex gap-2"><span className="text-emerald-400">●</span> Live: Governance, policy, evidence</div><div className="flex gap-2"><span className="text-yellow-400">●</span> Simulated: Signing, settlement</div><div className="flex gap-2"><span className="text-blue-400">●</span> Workshop: Custom policy</div><div className="flex gap-2"><span className="text-gray-500">●</span> Roadmap: Full PQC, HSM</div></div></GC>}
    <GC className="p-5 anim-d2"><SL>SANDBOX STATE</SL><div className="flex items-center justify-between"><div><div className="text-sm font-bold text-yellow-400">Reset Sandbox State</div><div className="fm text-xs text-gray-500">Clear all progress and evidence</div></div><Btn v="danger" onClick={()=>addLog({type:"warning",message:"Sandbox state reset"})}>RESET_SANDBOX</Btn></div></GC>
  </div>);
};

// ═══ MAIN ═══
export default function App() {
  const [phase, setPhase] = useState("landing");
  const [activeView, setActiveView] = useState("hub");
  const [activeScenario, setActiveScenario] = useState(null);
  const [auditLogs, setAuditLogs] = useState([]);
  const [fading, setFading] = useState(false);
  const addLog = useCallback((log) => { const time = new Date().toLocaleTimeString("en-US",{hour12:false,hour:"2-digit",minute:"2-digit",second:"2-digit"}); setAuditLogs(prev => [{...log,time},...prev]); }, []);
  const go = (to) => { setFading(true); setTimeout(() => { setPhase(to); setFading(false); }, 350); };
  const views = { "hub": <EvaluationHub setView={setActiveView} setScenario={setActiveScenario} addLog={addLog} />, "scenario-detail": <ScenarioDetail scenario={activeScenario} setView={setActiveView} addLog={addLog} />, "scenario-complete": <ScenarioComplete activeScenario={activeScenario} setView={setActiveView} setScenario={setActiveScenario} addLog={addLog} />, "overview": <EvalOverview activeScenario={activeScenario} setView={setActiveView} addLog={addLog} />, "assets": <AssetBoundary addLog={addLog} setView={setActiveView} />, "movement": <GovernedMovement activeScenario={activeScenario} addLog={addLog} setView={setActiveView} />, "participants": <GovParticipants addLog={addLog} />, "evidence": <EvidenceViewer activeScenario={activeScenario} addLog={addLog} setView={setActiveView} />, "config": <EvalConfig addLog={addLog} /> };

  return (<><style>{`@import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;700&family=Space+Grotesk:wght@300;400;500;600;700;900&display=swap');*{box-sizing:border-box;margin:0;padding:0}html{scroll-behavior:smooth}body,#root{background-color:#03040b;background-image:linear-gradient(rgba(255,255,255,.03) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.03) 1px,transparent 1px);background-size:32px 32px;color:#f8fafc;font-family:'Space Grotesk',sans-serif;min-height:100vh;overflow-x:hidden}.fm{font-family:'JetBrains Mono',monospace!important}.tg{background:linear-gradient(to right,#a855f7,#e879f9,#818cf8);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}.glass{background:rgba(15,10,30,.6);backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px);border:1px solid rgba(168,85,247,.2);box-shadow:inset 0 0 20px rgba(168,85,247,.05)}.glass-h:hover{border-color:rgba(168,85,247,.4);box-shadow:inset 0 0 30px rgba(168,85,247,.08),0 0 20px rgba(168,85,247,.1)}.glow{box-shadow:0 0 20px rgba(168,85,247,.4)}input,select,textarea{font-family:'JetBrains Mono',monospace;background:rgba(10,5,25,.8);border:1px solid rgba(168,85,247,.2);color:#f8fafc;padding:10px 14px;font-size:13px;outline:none;width:100%;transition:border-color .2s}input:focus,select:focus{border-color:rgba(168,85,247,.5);box-shadow:0 0 12px rgba(168,85,247,.15)}input::placeholder{color:#4b5563}::-webkit-scrollbar{width:6px}::-webkit-scrollbar-track{background:transparent}::-webkit-scrollbar-thumb{background:rgba(168,85,247,.3);border-radius:3px}@keyframes fadeUp{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:translateY(0)}}.anim{animation:fadeUp .5s ease-out forwards}.anim-d1{animation:fadeUp .5s ease-out .08s forwards;opacity:0}.anim-d2{animation:fadeUp .5s ease-out .16s forwards;opacity:0}.anim-d3{animation:fadeUp .5s ease-out .24s forwards;opacity:0}.anim-d4{animation:fadeUp .5s ease-out .32s forwards;opacity:0}@keyframes orbit1{to{transform:rotate3d(1,1,0,360deg)}}@keyframes orbit2{to{transform:rotate3d(1,-1,0,360deg)}}@keyframes orbit3{to{transform:rotate3d(0,1,1,360deg)}}.orb1{animation:orbit1 8s linear infinite}.orb2{animation:orbit2 10s linear infinite}.orb3{animation:orbit3 12s linear infinite}@keyframes pulse-ring{0%{box-shadow:0 0 0 0 rgba(168,85,247,.4)}70%{box-shadow:0 0 0 8px rgba(168,85,247,0)}100%{box-shadow:0 0 0 0 rgba(168,85,247,0)}}.pr{animation:pulse-ring 2s infinite}`}</style>
    <div style={{opacity:fading?0:1,transition:"opacity 0.35s ease"}}>
      {phase==="landing" && <LandingPage onEnterApp={()=>{addLog({type:"info",message:"Entered sandbox setup"});go("setup")}} />}
      {phase==="setup" && <div className="flex h-screen"><div className="flex-1 overflow-y-auto"><SandboxSetup onComplete={()=>{addLog({type:"success",message:"Evaluation Hub loaded"});go("app")}} addLog={addLog} /></div><div className="hidden lg:block border-l border-purple-500/20" style={{background:"rgba(5,2,15,.5)"}}><AuditLog logs={auditLogs} /></div></div>}
      {phase==="app" && <div className="flex flex-col h-screen"><div className="h-14 border-b border-purple-500/20 flex items-center justify-between px-5 flex-shrink-0" style={{background:"rgba(5,2,15,.8)"}}><div className="flex items-center gap-3"><span className="font-bold tracking-tight">QUANTUM_QUSTODY</span><span className="text-purple-500 fm" style={{animation:"pulse 2s infinite"}}>_</span><Badge c="fuchsia">SANDBOX</Badge>{activeScenario&&<><span className="text-gray-700 ml-2">|</span><span className="fm text-xs text-gray-500 ml-2">SCENARIO {activeScenario.num}</span></>}</div><div className="flex items-center gap-4 fm text-xs"><span className="text-gray-500">MODE:</span><span className="text-fuchsia-400">EVALUATION</span><span className="text-gray-700">|</span><span className="text-gray-500">TRUST:</span><span className="text-emerald-400 flex items-center gap-1"><span className="w-1.5 h-1.5 rounded-full bg-emerald-400 pr"/>CURRENT + PQC</span></div></div><div className="flex flex-1 overflow-hidden"><SideNav active={activeView} setActive={setActiveView} onLogout={()=>go("landing")} /><div className="flex-1 overflow-hidden flex flex-col">{views[activeView]}</div><div className="hidden lg:block border-l border-purple-500/20" style={{background:"rgba(5,2,15,.5)"}}><AuditLog logs={auditLogs} /></div></div></div>}
    </div></>);
}
